source 'https://github.com/WyICSP/WFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'WFReward_Example' do
  pod 'WFReward', :path => '../'

  target 'WFReward_Tests' do
    inherit! :search_paths

    
  end
end
